# Generated by Django 5.1.1 on 2024-10-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='ass', max_length=150, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
